server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/dynasty_forum
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapperLocations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql
