spring:
  datasource:
    url: jdbc:mysql://106.53.208.129:3306/dynasty_forum?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 5201314wjj
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 106.53.208.129
      port: 6379
      password: w939438965





