spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/dynasty_forum?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.56.10
      port: 6379





