server:
  port: 9999
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 10MB
mybatis-plus:
  mapperLocations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql
qq:
  oauth:
    authorizeUrl: https://graph.qq.com/oauth2.0/authorize
    backUrl: https://wcby.ruoqing.club/api/auth/qqLogin #回调，要和你申请的那个回调一致
    appId: 102104478
    appKey: Y2KPIxNZWEhvSlqg

xf:
  appId: c0c44c1a
  secret: MDI3ODlhZWVhMjM2N2I4YWU4ZDI0ZGVm
  uploadUrl: https://chatdoc.xfyun.cn/openapi/fileUpload

img:
  pt:
    url: https://www.imgtp.com/api/upload
    token: 8ad7492886d5f9b6e59932e62e2f14c6




