server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/dynasty_forum
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.56.10
      port: 6379
mybatis-plus:
  mapperLocations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql
qq:
  oauth:
    authorizeUrl: https://graph.qq.com/oauth2.0/authorize
    backUrl: http://ruoqing.club/auth/qqLogin #回调，要和你申请的那个回调一致
    appId: 102104478
    appKey: Y2KPIxNZWEhvSlqg

xf:
  appId: c0c44c1a
  secret: MDI3ODlhZWVhMjM2N2I4YWU4ZDI0ZGVm
  uploadUrl: https://chatdoc.xfyun.cn/openapi/fileUpload
